name: Auto Run Bot Saham 2x Sehari

on:
  schedule:
    - cron: '30 2 * * 1-5'
    - cron: '0 7 * * 1-5'
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          pip install yfinance ta requests pandas

      - name: Run Bot Saham
        run: python bot_saham.py
