name: Auto Run Bot Saham

on:
  schedule:
    - cron: '30 2 * * *'  # 09:30 WIB (UTC+7)
    - cron: '0 7 * * *'   # 14:00 WIB (UTC+7)
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install yfinance ta requests pandas

      - name: Run bot script
        run: python bot_saham.py
